<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_slider_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_slider by id_slider
     */
    function get_tbl_slider($id_slider)
    {
        return $this->db->get_where('tbl_slider',array('id_slider'=>$id_slider))->row_array();
    }
        
    /*
     * Get all tbl_slider
     */
    function get_all_tbl_slider()
    {
        $this->db->order_by('id_slider', 'desc');
        return $this->db->get('tbl_slider')->result_array();
    }
        
    /*
     * function to add new tbl_slider
     */
    function add_tbl_slider($params)
    {
        $this->db->insert('tbl_slider',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_slider
     */
    function update_tbl_slider($id_slider,$params)
    {
        $this->db->where('id_slider',$id_slider);
        return $this->db->update('tbl_slider',$params);
    }
    
    /*
     * function to delete tbl_slider
     */
    function delete_tbl_slider($id_slider)
    {
        return $this->db->delete('tbl_slider',array('id_slider'=>$id_slider));
    }
}
