<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Adm_joinus extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_joinus_model');
        $this->load->database();
        $this->load->helper('url');
        
        if (!$this->session->userdata('logged')) {            
            $this->session->set_flashdata('message','Silahkan login untuk memulai!');
            $this->session->set_flashdata('error','animated headShake red-box');
            //$this->index();
            redirect('login');
        }
    } 

    /*
     * Listing of tbl_joinus
     */
    function index()
    {        
        $data['tbl_joinus'] = $this->Tbl_joinus_model->get_tbl_joinus(1);
        if(isset($data['tbl_joinus']['id_joinus']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'joinus_title_id' => $this->input->post('joinus_title_id'),
                    'joinus_desc_id' => $this->input->post('joinus_desc_id'),
                    'joinus_title_en' => $this->input->post('joinus_title_en'),
                    'joinus_desc_en' => $this->input->post('joinus_desc_en'),
                );

                $this->Tbl_joinus_model->update_tbl_joinus(1,$params);            
                redirect('admin/joinus');
            }
            else
            {
                $data = array(
                    "site" => $_SERVER['SERVER_NAME'],
                    "page" => "JoinUs",
                    "tbl_joinus" => $this->Tbl_joinus_model->get_tbl_joinus(1)
                );
                
                $this->load->view('layout/admin/header', $data);
                $this->load->view('edit', $data);
                $this->load->view('layout/admin/footer');
            }
        }
        else
            show_error('The Tbl_joinus you are trying to edit does not exist.');
    }  
    
}
