<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_gallery_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_gallery by id_gallery
     */
    function get_tbl_gallery($id_gallery)
    {
        return $this->db->get_where('tbl_gallery',array('id_gallery'=>$id_gallery))->row_array();
    }
        
    /*
     * Get all tbl_gallery
     */
    function get_all_tbl_gallery()
    {
        $this->db->order_by('id_gallery', 'desc');
        return $this->db->get('tbl_gallery')->result_array();
    }
        
    /*
     * function to add new tbl_gallery
     */
    function get_tbl_gallery_id($id_gallery)
    {
        $this->db->where('id_gallery', $id_gallery);
        return $this->db->get('tbl_gallery_img');
    }


    function get_tbl_gallery_img($id_gallery)
    {
        return $this->db->get_where('tbl_gallery_img',array('id_img'=>$id_gallery))->row_array();
    }


    function add_tbl_gallery($params)
    {
        $this->db->insert('tbl_gallery',$params);
        $insert_id = $this->db->insert_id();
        return $insert_id;
    }
    
    /*
     * function to update tbl_gallery
     */
    function update_tbl_gallery($id_gallery,$params)
    {
        $this->db->where('id_gallery',$id_gallery);
        return $this->db->update('tbl_gallery',$params);
    }
    
    /*
     * function to delete tbl_gallery
     */
    function delete_tbl_gallery($id_gallery)
    {
        return $this->db->delete('tbl_gallery',array('id_gallery'=>$id_gallery));
    }
    function delete_tbl_gallery_img($id_img)
    {
        return $this->db->delete('tbl_gallery_img',array('id_img'=>$id_img));
    }
}
