<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_kemitraan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_kemitraan by id_kemitraan
     */
    function get_tbl_kemitraan($id_kemitraan)
    {
        return $this->db->get_where('tbl_kemitraan',array('id_kemitraan'=>$id_kemitraan))->row_array();
    }
        
    /*
     * Get all tbl_kemitraan
     */
    function get_all_tbl_kemitraan()
    {
        $this->db->order_by('id_kemitraan', 'desc');
        return $this->db->get('tbl_kemitraan')->result_array();
    }
        
    /*
     * function to add new tbl_kemitraan
     */
    function add_tbl_kemitraan($params)
    {
        $this->db->insert('tbl_kemitraan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_kemitraan
     */
    function update_tbl_kemitraan($id_kemitraan,$params)
    {
        $this->db->where('id_kemitraan',$id_kemitraan);
        return $this->db->update('tbl_kemitraan',$params);
    }
    
    /*
     * function to delete tbl_kemitraan
     */
    function delete_tbl_kemitraan($id_kemitraan)
    {
        return $this->db->delete('tbl_kemitraan',array('id_kemitraan'=>$id_kemitraan));
    }

    function get_all_tbl_kemitraan_img()
    {
        $this->db->order_by('id_kemitraan', 'desc');
        return $this->db->get('tbl_kemitraan_img')->result_array();
    }
    function get_tbl_kemitraan_img($id_kemitraan)
    {
        $this->db->where('id_mitra',$id_kemitraan);
        $this->db->order_by('id_mitra', 'desc');
        return $this->db->get('tbl_kemitraan_img')->result_array();
    }
    function get_tbl_kemitraan_id_img($id_img)
    {
        return $this->db->get_where('tbl_kemitraan_img',array('id_img'=>$id_img))->row_array();
    }
        
    /*
     * function to add new tbl_kemitraan
     */
    function add_tbl_kemitraan_img($params)
    {
        $this->db->insert('tbl_kemitraan_img',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_kemitraan
     */
    function update_tbl_kemitraan_img($id_kemitraan,$params)
    {
        $this->db->where('id_kemitraan',$id_kemitraan);
        return $this->db->update('tbl_kemitraan_img',$params);
    }
    
    /*
     * function to delete tbl_kemitraan
     */
    function delete_tbl_kemitraan_img($id_kemitraan)
    {
        return $this->db->delete('tbl_kemitraan_img',array('id_img'=>$id_kemitraan));
    }
}
