<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Adm_ourpartner extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_ourpartner_model');
        $this->load->helper("file");
        if (!$this->session->userdata('logged')) {            
            $this->session->set_flashdata('message','Silahkan login untuk memulai!');
            $this->session->set_flashdata('error','animated headShake red-box');
            //$this->index();
            redirect('login');
        }
    } 

    /*
     * Listing of tbl_ourpartner
     */
    function index()
    {
        $data = array(
            "site" => $_SERVER['SERVER_NAME'],
            "page" => "Our Partner",
            "tbl_ourpartner" => $this->Tbl_ourpartner_model->get_all_tbl_ourpartner()
        );
        
        $this->load->view('layout/admin/header', $data);
        $this->load->view('index', $data);
        $this->load->view('layout/admin/footer');
    }

    /*
     * Adding a new tbl_ourpartner
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {
            $config['upload_path']          = './uploads/';
            $config['allowed_types']        = 'gif|jpg|png';
            $config['max_size']             = 0;
            $config['max_width']            = 0;
            $config['max_height']           = 0;
            $config['overwrite']     = FALSE;
            //
            $this->load->library('upload', $config);

            $data = array('upload_data' => $this->upload->data());
            $params = array(
                'ourpartner_name' => $this->input->post('ourpartner_name'),
                'ourpartner_img' => $this->upload->data('file_name'),
                'ourpartner_desc_id' => $this->input->post('ourpartner_desc_id'),
                'ourpartner_desc_en' => $this->input->post('ourpartner_desc_en'),
            );

            $files = $_FILES;
            for($i=0; $i< count($_FILES['ourpartner_img']['name']); $i++)
            {           
                $_FILES['userfile']['name']= $files['ourpartner_img']['name'][$i];
                $_FILES['userfile']['type']= $files['ourpartner_img']['type'][$i];
                $_FILES['userfile']['tmp_name']= $files['ourpartner_img']['tmp_name'][$i];
                $_FILES['userfile']['error']= $files['ourpartner_img']['error'][$i];
                $_FILES['userfile']['size']= $files['ourpartner_img']['size'][$i];    

                $this->upload->initialize($config);
                //$this->upload->do_upload();
                $data = array('upload_data' => $this->upload->data());  
                $params = array(
                    'ourpartner_name' => $this->input->post('ourpartner_name'),
                    'ourpartner_img' => $files['ourpartner_img']['name'][$i],
                    'ourpartner_desc_id' => $this->input->post('ourpartner_desc_id'),
                    'ourpartner_desc_en' => $this->input->post('ourpartner_desc_en'),
                );
                $tbl_ourpartner_id = $this->Tbl_ourpartner_model->add_tbl_ourpartner($params);
            }
            
            redirect('admin/OurClient');
            /*
            //upload file
            $i = 0;
            $files = array();
            $is_file_error = FALSE;
 
            if ($_FILES['ourpartner_img']['size'] <= 0) {
                $this->handle_error('Select at least one file.');
            } else {
                foreach ($_FILES as $key => $value) {
                    if (!empty($value['name'])) {
                        $this->load->library('upload', $config);
                        if (!$this->upload->do_upload($key)) {
                            $this->handle_error($this->upload->display_errors());
                            $is_file_error = TRUE;
                        } else {
                            $files[$i] = $this->upload->data();

                            $params = array(
                                'ourpartner_name' => $this->input->post('ourpartner_name'),
                                'ourpartner_img' => $files[$i]['filename'],
                                'ourpartner_desc_id' => $this->input->post('ourpartner_desc_id'),
                                'ourpartner_desc_en' => $this->input->post('ourpartner_desc_en'),
                            );
                            
                            $tbl_ourpartner_id = $this->Tbl_ourpartner_model->add_tbl_ourpartner($params);
                            ++$i;
                        }
                    }
                }
            }*/
        }
        else
        {            
            $data = array(
                "site" => $_SERVER['SERVER_NAME'],
                "page" => "Product"
            );
            
            $this->load->view('layout/admin/header', $data);
            $this->load->view('add', $data);
            $this->load->view('layout/admin/footer');
        }
    }  

    /*
     * Editing a tbl_ourpartner
     */
    function edit($id_ourpartner)
    {   
        // check if the tbl_ourpartner exists before trying to edit it
        $data['tbl_ourpartner'] = $this->Tbl_ourpartner_model->get_tbl_ourpartner($id_ourpartner);
        
        if(isset($data['tbl_ourpartner']['id_ourpartner']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {

                $config['upload_path']          = './uploads/';
                $config['allowed_types']        = 'gif|jpg|png';
                $config['max_size']             = 100;
                $config['max_width']            = 1024;
                $config['max_height']           = 768;

                $this->load->library('upload', $config);

                if (!$this->upload->do_upload('ourpartner_img'))
                {
                    $params = array(
                        'ourpartner_name' => $this->input->post('ourpartner_name'),
                        'ourpartner_desc_id' => $this->input->post('ourpartner_desc_id'),
                        'ourpartner_desc_en' => $this->input->post('ourpartner_desc_en'),
                    );
                    
                    $this->Tbl_ourpartner_model->update_tbl_ourpartner($id_ourpartner,$params); 
                    redirect('admin/OurPartner');
                }
                else
                {
                    $data = array('upload_data' => $this->upload->data());
                    $params = array(
                        'ourpartner_name' => $this->input->post('ourpartner_name'),
                        'ourpartner_img' => $this->upload->data('file_name'),
                        'ourpartner_desc_id' => $this->input->post('ourpartner_desc_id'),
                        'ourpartner_desc_en' => $this->input->post('ourpartner_desc_en'),
                    );
                    
                    $this->Tbl_ourpartner_model->update_tbl_ourpartner($id_ourpartner,$params);  
                    redirect('admin/OurPartner');
                }
            }
            else
            {
                $data = array(
                    "site" => $_SERVER['SERVER_NAME'],
                    "page" => "OurPartner",
                    "tbl_ourpartner" => $this->Tbl_ourpartner_model->get_tbl_ourpartner($id_ourpartner)
                );
                
                $this->load->view('layout/admin/header', $data);
                $this->load->view('edit', $data);
                $this->load->view('layout/admin/footer');
            }
        }
        else
            show_error('The tbl_ourpartner you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_ourpartner
     */
    function remove($id_ourpartner)
    {
        $tbl_ourpartner = $this->Tbl_ourpartner_model->get_tbl_ourpartner($id_ourpartner);

        // check if the tbl_ourpartner exists before trying to delete it
        if(isset($tbl_ourpartner['id_ourpartner']))
        {
            unlink('./uploads/'.$tbl_ourpartner['ourpartner_img']);
            $this->Tbl_ourpartner_model->delete_tbl_ourpartner($id_ourpartner);
            redirect('admin/OurPartner');
        }
        else
            show_error('The tbl_ourpartner you are trying to delete does not exist.');
    }
    
}
