<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Adm_faq extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_faq_model');
        
        if (!$this->session->userdata('logged')) {            
            $this->session->set_flashdata('message','Silahkan login untuk memulai!');
            $this->session->set_flashdata('error','animated headShake red-box');
            //$this->index();
            redirect('login');
        }
    } 

    /*
     * Listing of tbl_faq
     */
    function index()
    {
        $data = array(
            "site" => $_SERVER['SERVER_NAME'],
            "page" => "FAQ",
            "tbl_faq" => $this->Tbl_faq_model->get_all_tbl_faq()
        );
        
        $this->load->view('layout/admin/header', $data);
        $this->load->view('index', $data);
        $this->load->view('layout/admin/footer');
    }

    /*
     * Adding a new tbl_faq
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'question_id' => $this->input->post('question_id'),
                'question_en' => $this->input->post('question_en'),
                'answer_id' => $this->input->post('answer_id'),
                'answer_en' => $this->input->post('answer_en'),
            );
            
            $tbl_faq_id = $this->Tbl_faq_model->add_tbl_faq($params);
            redirect('admin/faq');
        }
        else
        {            
            $data = array(
                "site" => $_SERVER['SERVER_NAME'],
                "page" => "FAQ"
            );
            
            $this->load->view('layout/admin/header', $data);
            $this->load->view('add', $data);
            $this->load->view('layout/admin/footer');
        }
    }  

    /*
     * Editing a tbl_faq
     */
    function edit($id_faq)
    {   
        // check if the tbl_faq exists before trying to edit it
        $data['tbl_faq'] = $this->Tbl_faq_model->get_tbl_faq($id_faq);
        
        if(isset($data['tbl_faq']['id_faq']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {                   
                $params = array(
                    'question_id' => $this->input->post('question_id'),
                    'question_en' => $this->input->post('question_en'),
                    'answer_id' => $this->input->post('answer_id'),
                    'answer_en' => $this->input->post('answer_en'),
                );

                $this->Tbl_faq_model->update_tbl_faq($id_faq,$params);            
                redirect('admin/faq');
            }
            else
            {
                $data = array(
                    "site" => $_SERVER['SERVER_NAME'],
                    "page" => "FAQ",
                    "tbl_faq" => $this->Tbl_faq_model->get_tbl_faq($id_faq)
                );
                
                $this->load->view('layout/admin/header', $data);
                $this->load->view('edit', $data);
                $this->load->view('layout/admin/footer');
            }
        }
        else
            show_error('The tbl_faq you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_faq
     */
    function remove($id_faq)
    {
        $tbl_faq = $this->Tbl_faq_model->get_tbl_faq($id_faq);

        // check if the tbl_faq exists before trying to delete it
        if(isset($tbl_faq['id_faq']))
        {
            $this->Tbl_faq_model->delete_tbl_faq($id_faq);
            redirect('admin/faq');
        }
        else
            show_error('The tbl_faq you are trying to delete does not exist.');
    }
    
}
