<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Adm_gallery extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_gallery_model');
        if (!$this->session->userdata('logged')) {            
            $this->session->set_flashdata('message','Silahkan login untuk memulai!');
            $this->session->set_flashdata('error','animated headShake red-box');
            //$this->index();
            redirect('login');
        }
    } 

    /*
     * Listing of tbl_gallery
     */
    function index()
    {
        $data = array(
            "site" => $_SERVER['SERVER_NAME'],
            "page" => "Gallery",
            "tbl_gallery" => $this->Tbl_gallery_model->get_all_tbl_gallery()
        );
        
        $this->load->view('layout/admin/header', $data);
        $this->load->view('index', $data);
        $this->load->view('layout/admin/footer');
    }

    /*
     * Adding a new tbl_gallery
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {        

            $params = array(
                'gallery_title_id' => $this->input->post('gallery_title_id'),
                'gallery_title_en' => $this->input->post('gallery_title_en'),
                'gallery_desc_id' => $this->input->post('gallery_desc_id'),
                'gallery_desc_en' => $this->input->post('gallery_desc_en'),
            );
            
            $Tbl_gallery_id = $this->Tbl_gallery_model->add_tbl_gallery($params);

            if($Tbl_gallery_id)
            {
                $this->session->set_flashdata('pesan', 'toastr.success("Berhasil Menambah", "Success")');
            }else{
                $this->session->set_flashdata('pesan', 'toastr.error("Gagal Menambah", "Error")');
            }
            redirect('admin/gallery');
        }
        else
        {            
            $data = array(
                "site" => $_SERVER['SERVER_NAME'],
                "page" => "Gallery"
            );
            
            $this->load->view('layout/admin/header', $data);
            $this->load->view('add', $data);
            $this->load->view('layout/admin/footer');
        }
    }

    function gallery_upload($id_gallery)
    {
        if (!empty($_FILES)) {
            $tempFile = $_FILES['file']['tmp_name'];
            $fileName = $_FILES['file']['name'];
            $fileName = rand(1,1000).md5($fileName).'_'.$fileName;
            $targetPath = getcwd() . '/uploads/';
            $targetFile = $targetPath . $fileName ;
            move_uploaded_file($tempFile, $targetFile);
            // if you want to save in db,where here
            // with out model just for example
            $this->load->database(); // load database
            $this->db->insert('tbl_gallery_img',array('id_gallery' => $id_gallery, 'image' => $fileName));
            redirect('admin/gallery_upload/'.$id_gallery);
        }
        else
        {            
            $data = array(
                "site" => $_SERVER['SERVER_NAME'],
                "page" => "Image Gallery",
                "image" => $this->Tbl_gallery_model->get_tbl_gallery_id($id_gallery),
                "gallery" => $this->Tbl_gallery_model->get_tbl_gallery($id_gallery),
            );
            
            $this->load->view('layout/admin/header', $data);
            $this->load->view('upload', $data);
            $this->load->view('layout/admin/footer');
        }
    }

    function remove_upload($id_img, $id_gallery)
    {
        $tbl_gallery = $this->Tbl_gallery_model->get_tbl_gallery_img($id_img);

        // check if the tbl_home exists before trying to delete it
        if(isset($tbl_gallery['id_img']))
        {   
            
            unlink('/home/arlindo/public_html/uploads/'.$tbl_gallery['image']);
            $this->Tbl_gallery_model->delete_tbl_gallery_img($id_img);
            redirect('admin/gallery_upload/'.$id_gallery);
            
            //echo getcwd();
            
        }
        else
            show_error('The home you are trying to delete does not exist.');
    }

    /*
     * Editing a tbl_gallery
     */
    function edit($id_gallery)
    {   
        // check if the tbl_gallery exists before trying to edit it
        $data['tbl_gallery'] = $this->Tbl_gallery_model->get_tbl_gallery($id_gallery);
        
        if(isset($data['tbl_gallery']['id_gallery']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {         
                $config['upload_path']          = './uploads/';
                $config['allowed_types']        = 'gif|jpg|png';

                $this->load->library('upload', $config);

                if ( ! $this->upload->do_upload('gallery_img'))
                {
                    $params = array(
                        'gallery_title_id' => $this->input->post('gallery_title_id'),
                        'gallery_title_en' => $this->input->post('gallery_title_en'),
                        'gallery_desc_id' => $this->input->post('gallery_desc_id'),
                        'gallery_desc_en' => $this->input->post('gallery_desc_en'),
                    );
                    
                    $Tbl_gallery_id = $this->Tbl_gallery_model->update_tbl_gallery($id_gallery,$params);
                }
                else
                {
                    $data = array('upload_data' => $this->upload->data());
                    $params = array(
                        'gallery_title_id' => $this->input->post('gallery_title_id'),
                        'gallery_title_en' => $this->input->post('gallery_title_en'),
                        'gallery_img' => $this->upload->data('file_name'),
                        'gallery_desc_id' => $this->input->post('gallery_desc_id'),
                        'gallery_desc_en' => $this->input->post('gallery_desc_en'),
                    );
                    
                    $Tbl_gallery_id = $this->Tbl_gallery_model->update_tbl_gallery($id_gallery,$params);
                }

                if($Tbl_gallery_id)
                {
                    $this->session->set_flashdata('pesan', 'toastr.success("Berhasil Mengubah", "Success")');
                }else{
                    $this->session->set_flashdata('pesan', 'toastr.error("Gagal Mengubah", "Error")');
                }
                redirect('admin/gallery');
            }
            else
            {
                $data = array(
                    "site" => $_SERVER['SERVER_NAME'],
                    "page" => "Gallery",
                    "tbl_gallery" => $this->Tbl_gallery_model->get_tbl_gallery($id_gallery)
                );
                
                $this->load->view('layout/admin/header', $data);
                $this->load->view('edit', $data);
                $this->load->view('layout/admin/footer');
            }
        }
        else
            show_error('The tbl_gallery you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_gallery
     */
    function remove($id_gallery)
    {
        $tbl_gallery = $this->Tbl_gallery_model->get_tbl_gallery($id_gallery);

        // check if the tbl_gallery exists before trying to delete it
        if(isset($tbl_gallery['id_gallery']))
        {
            if($tbl_gallery['gallery_img'] != '' || $tbl_gallery['gallery_img'] != null){
                unlink('/home/sayuransiapsaji/public_html/uploads/'.$tbl_gallery['gallery_img']);                
            }
            $Tbl_gallery_id = $this->Tbl_gallery_model->delete_tbl_gallery($id_gallery);
            
            if($Tbl_gallery_id)
            {
                $this->session->set_flashdata('pesan', 'toastr.success("Berhasil Menghapus", "Success")');
            }else{
                $this->session->set_flashdata('pesan', 'toastr.error("Gagal Menghapus", "Error")');
            }
            redirect('admin/gallery');
        }
        else
            show_error('The tbl_gallery you are trying to delete does not exist.');
    }
    
}
