<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_news_img extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_news_img_model');
        if (!$this->session->userdata('logged')) {            
            $this->session->set_flashdata('message','Silahkan login untuk memulai!');
            $this->session->set_flashdata('error','animated headShake red-box');
            //$this->index();
            redirect('login');
        }
    } 

    /*
     * Listing of tbl_news_img
     */
    function index()
    {
        $data['tbl_news_img'] = $this->Tbl_news_img_model->get_all_tbl_news_img();
        
        $data['_view'] = 'tbl_news_img/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_news_img
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_news' => $this->input->post('id_news'),
				'image' => $this->input->post('image'),
            );
            
            $tbl_news_img_id = $this->Tbl_news_img_model->add_tbl_news_img($params);
            redirect('tbl_news_img/index');
        }
        else
        {            
            $data['_view'] = 'tbl_news_img/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_news_img
     */
    function edit($id_img)
    {   
        // check if the tbl_news_img exists before trying to edit it
        $data['tbl_news_img'] = $this->Tbl_news_img_model->get_tbl_news_img($id_img);
        
        if(isset($data['tbl_news_img']['id_img']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_news' => $this->input->post('id_news'),
					'image' => $this->input->post('image'),
                );

                $this->Tbl_news_img_model->update_tbl_news_img($id_img,$params);            
                redirect('tbl_news_img/index');
            }
            else
            {
                $data['_view'] = 'tbl_news_img/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_news_img you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_news_img
     */
    function remove($id_img)
    {
        $tbl_news_img = $this->Tbl_news_img_model->get_tbl_news_img($id_img);

        // check if the tbl_news_img exists before trying to delete it
        if(isset($tbl_news_img['id_img']))
        {
            if($tbl_news_img['id_img'] != '' || $tbl_news_img['id_img'] != null){
                unlink('/home/sayuransiapsaji/public_html/uploads/'.$tbl_news_img['id_img']);                
            }
            $Tbl_product_id = $this->Tbl_news_img_model->delete_tbl_news_img($id_img);
            
            if($Tbl_product_id)
            {
                $this->session->set_flashdata('pesan', 'toastr.success("Berhasil Menghapus Produk", "Success")');
            }else{
                $this->session->set_flashdata('pesan', 'toastr.error("Gagal Menghapus Produk", "Error")');
            }
            redirect('tbl_news_img/index');
        }
        else
            show_error('The tbl_news_img you are trying to delete does not exist.');
    }
    
}
