<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Adm_kemitraan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_kemitraan_model');
        if (!$this->session->userdata('logged')) {            
            $this->session->set_flashdata('message','Silahkan login untuk memulai!');
            $this->session->set_flashdata('error','animated headShake red-box');
            //$this->index();
            redirect('login');
        }
    } 

    /*
     * Listing of tbl_kemitraan
     */
    function index()
    {
        $data = array(
            "site" => $_SERVER['SERVER_NAME'],
            "page" => "Kemitraan",
            "tbl_kemitraan" => $this->Tbl_kemitraan_model->get_all_tbl_kemitraan()
        );
        
        $this->load->view('layout/admin/header', $data);
        $this->load->view('index', $data);
        $this->load->view('layout/admin/footer');
    }


    /*
     * Adding a new tbl_kemitraan
     */

    private function set_upload_options() {
        // upload an image options
        $config = array ();
        $config ['upload_path'] = './uploads/kemitraan/';
        $config ['allowed_types'] = 'gif|jpg|png';

        return $config;
    }

    /*function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {
            $this->load->library('upload');
            
            $files = $_FILES;

            $cpt = count ( $_FILES ['kemitraan_img'] ['name'] );
            for($i = 0; $i < $cpt; $i ++) {

                $_FILES ['images'] ['name'] = $files ['kemitraan_img'] ['name'] [$i];
                $_FILES ['images'] ['type'] = $files ['kemitraan_img'] ['type'] [$i];
                $_FILES ['images'] ['tmp_name'] = $files ['kemitraan_img'] ['tmp_name'] [$i];
                $_FILES ['images'] ['error'] = $files ['kemitraan_img'] ['error'] [$i];
                $_FILES ['images'] ['size'] = $files ['kemitraan_img'] ['size'] [$i];

                $this->upload->initialize($this->set_upload_options());
                if($this->upload->do_upload('images'))
                {

                    $params = array(
                        'kemitraan_title_id' => $this->input->post('kemitraan_title_id'),
                        'kemitraan_title_en' => $this->input->post('kemitraan_title_en'),
                        'kemitraan_desc_id' => $this->input->post('kemitraan_desc_id'),
                        'kemitraan_desc_en' => $this->input->post('kemitraan_desc_en'),
                    );
                    
                    $params = array(
                        'id_mitra' => 1,
                        'image' =>  $_FILES['images']['name']
                    );
                    $this->Tbl_kemitraan_model->add_tbl_kemitraan_img($params);
                    $this->session->set_flashdata('pesan', 'toastr.success("Berhasil menyimpan mitra.", "success");');
                }else{

                    $params = array(
                        'kemitraan_title_id' => $this->input->post('kemitraan_title_id'),
                        'kemitraan_title_en' => $this->input->post('kemitraan_title_en'),
                        'kemitraan_desc_id' => $this->input->post('kemitraan_desc_id'),
                        'kemitraan_desc_en' => $this->input->post('kemitraan_desc_en'),
                    );

                    $this->Tbl_kemitraan_model->add_tbl_kemitraan_img($params);
                    $this->session->set_flashdata('pesan', 'toastr.error("Gagal menyimpan mitra.", "Error");');
                }
            }
            redirect('admin/kemitraan');
        }
        else
        {            
            $data = array(
                "site" => $_SERVER['SERVER_NAME'],
                "page" => "Add Mitra"
            );
            
            $this->load->view('layout/admin/header', $data);
            $this->load->view('add', $data);
            $this->load->view('layout/admin/footer');
        }
    }*/

    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {
            $config['upload_path']          = './uploads/';
            $config['allowed_types']        = 'gif|jpg|png';
            $config['max_size']             = 100;
            $config['max_width']            = 1024;
            $config['max_height']           = 768;

            $this->load->library('upload', $config);

            if ( ! $this->upload->do_upload('kemitraan_img'))
            {
                $params = array(
                    'kemitraan_title_id' => $this->input->post('kemitraan_title_id'),
                    'kemitraan_title_en' => $this->input->post('kemitraan_title_id'),
                    'kemitraan_desc_id' => $this->input->post('kemitraan_desc_id'),
                    'kemitraan_desc_en' => $this->input->post('kemitraan_desc_en'),
                    'email' => $this->input->post('email'),
                    'alamat' => $this->input->post('alamat'),
                    'telp' => $this->input->post('telp'),
                );
                
                $this->Tbl_kemitraan_model->add_tbl_kemitraan($params);
                redirect('admin/kemitraan');
            }
            else
            {
                $data = array('upload_data' => $this->upload->data());
                $params = array(
                    'kemitraan_title_id' => $this->input->post('kemitraan_title_id'),
                    'kemitraan_title_en' => $this->input->post('kemitraan_title_id'),
                    'kemitraan_img' => $this->upload->data('file_name'),
                    'kemitraan_desc_id' => $this->input->post('kemitraan_desc_id'),
                    'kemitraan_desc_en' => $this->input->post('kemitraan_desc_en'),
                );
                
                $this->Tbl_kemitraan_model->add_tbl_kemitraan($params);
                redirect('admin/kemitraan');
            }
        }
        else
        {            
            $data = array(
                "site" => $_SERVER['SERVER_NAME'],
                "page" => "Add Mitra"
            );
            
            $this->load->view('layout/admin/header', $data);
            $this->load->view('add', $data);
            $this->load->view('layout/admin/footer');
        }
    }

    function kemitraan_upload($id_mitra)
    {
        if (!empty($_FILES)) {
            $tempFile = $_FILES['file']['tmp_name'];
            $fileName = $_FILES['file']['name'];
            $fileName = rand(1,1000).md5($fileName).'_'.$fileName;
            $targetPath = getcwd() . '/uploads/';
            $targetFile = $targetPath . $fileName ;
            move_uploaded_file($tempFile, $targetFile);
            // if you want to save in db,where here
            // with out model just for example
            $this->load->database(); // load database
            $this->db->insert('tbl_kemitraan_img',array('id_mitra' => $id_mitra, 'image' => $fileName));
            redirect('admin/kemitraan_upload/'.$id_mitra);
        }
        else
        {            
            $data = array(
                "site" => $_SERVER['SERVER_NAME'],
                "page" => "Image Mitra",
                "image" => $this->Tbl_kemitraan_model->get_tbl_kemitraan_img($id_mitra),
                "mitra" => $this->Tbl_kemitraan_model->get_tbl_kemitraan($id_mitra),
            );
            
            $this->load->view('layout/admin/header', $data);
            $this->load->view('upload', $data);
            $this->load->view('layout/admin/footer');
        }
    }

    function remove_upload($id_img, $id_mitra)
    {
        $tbl_mitra = $this->Tbl_kemitraan_model->get_tbl_kemitraan_id_img($id_img);

        // check if the tbl_home exists before trying to delete it
        if(isset($tbl_mitra['id_img']))
        {   
            unlink('/home/sayuransiapsaji/public_html/uploads/'.$tbl_mitra['image']);
            $this->Tbl_kemitraan_model->delete_tbl_kemitraan_img($id_img);
            redirect('admin/kemitraan_upload/'.$id_mitra);
            
        }
        else
            show_error('The home you are trying to delete does not exist.');
    }


    /*
     * Editing a tbl_kemitraan
     */
    function edit($id_kemitraan)
    {   
        // check if the tbl_kemitraan exists before trying to edit it
        $data['tbl_kemitraan'] = $this->Tbl_kemitraan_model->get_tbl_kemitraan($id_kemitraan);
        
        if(isset($data['tbl_kemitraan']['id_kemitraan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {         
                $config['upload_path']          = './uploads/';
                $config['allowed_types']        = 'gif|jpg|png';
                $config['max_size']             = 100;
                $config['max_width']            = 1024;
                $config['max_height']           = 768;

                $this->load->library('upload', $config);

                if ( ! $this->upload->do_upload('kemitraan_img'))
                {
                    $params = array(
                        'kemitraan_title_id' => $this->input->post('kemitraan_title_id'),
                        'kemitraan_title_en' => $this->input->post('kemitraan_title_id'),
                        'kemitraan_desc_id' => $this->input->post('kemitraan_desc_id'),
                        'kemitraan_desc_en' => $this->input->post('kemitraan_desc_en'),
                        'email' => $this->input->post('email'),
                        'alamat' => $this->input->post('alamat'),
                        'telp' => $this->input->post('telp'),
                    );
                    
                    $this->Tbl_kemitraan_model->update_tbl_kemitraan($id_kemitraan,$params);
                    redirect('admin/kemitraan');
                }
                else
                {
                    $data = array('upload_data' => $this->upload->data());
                    $params = array(
                        'kemitraan_title_id' => $this->input->post('kemitraan_title_id'),
                        'kemitraan_title_en' => $this->input->post('kemitraan_title_id'),
                        'kemitraan_img' => $this->upload->data('file_name'),
                        'kemitraan_desc_id' => $this->input->post('kemitraan_desc_id'),
                        'kemitraan_desc_en' => $this->input->post('kemitraan_desc_en'),
                    );
                    
                    $this->Tbl_kemitraan_model->update_tbl_kemitraan($id_kemitraan,$params);
                    redirect('admin/kemitraan');
                }
            }
            else
            {
                $data = array(
                    "site" => $_SERVER['SERVER_NAME'],
                    "page" => "Kemitraan",
                    "tbl_kemitraan" => $this->Tbl_kemitraan_model->get_tbl_kemitraan($id_kemitraan)
                );
                
                $this->load->view('layout/admin/header', $data);
                $this->load->view('edit', $data);
                $this->load->view('layout/admin/footer');
            }
        }
        else
            show_error('The tbl_kemitraan you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_kemitraan
     */
    function remove($id_kemitraan)
    {
        $tbl_kemitraan = $this->Tbl_kemitraan_model->get_tbl_kemitraan($id_kemitraan);

        // check if the tbl_kemitraan exists before trying to delete it
        if(isset($tbl_kemitraan['id_kemitraan']))
        {
            $this->Tbl_kemitraan_model->delete_tbl_kemitraan($id_kemitraan);
            redirect('admin/kemitraan');
        }
        else
            show_error('The tbl_kemitraan you are trying to delete does not exist.');
    }

    function remove_img($id_kemitraan,$link)
    {
        $tbl_kemitraan = $this->Tbl_kemitraan_model->get_tbl_kemitraan($id_kemitraan);

        // check if the tbl_kemitraan exists before trying to delete it
        if(isset($tbl_kemitraan['id_kemitraan']))
        {            

            if($tbl_kemitraan['kemitraan_img'] != '' || $tbl_kemitraan['kemitraan_img'] != null){
                unlink('/home/sayuransiapsaji/public_html/uploads/'.$tbl_kemitraan['kemitraan_img']);                
            }
            $Tbl_product_id = $this->Tbl_kemitraan_model->delete_tbl_kemitraan($id_kemitraan);
            
            if($Tbl_product_id)
            {
                $this->session->set_flashdata('pesan', 'toastr.success("Berhasil Menghapus Produk", "Success")');
            }else{
                $this->session->set_flashdata('pesan', 'toastr.error("Gagal Menghapus Produk", "Error")');
            }
            redirect($link);
        }
        else
            show_error('The tbl_kemitraan you are trying to delete does not exist.');
    }
    
}
