<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_faq_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_faq by id_faq
     */
    function get_tbl_faq($id_faq)
    {
        return $this->db->get_where('tbl_faq',array('id_faq'=>$id_faq))->row_array();
    }
        
    /*
     * Get all tbl_faq
     */
    function get_all_tbl_faq()
    {
        $this->db->order_by('id_faq', 'desc');
        return $this->db->get('tbl_faq')->result_array();
    }
        
    /*
     * function to add new tbl_faq
     */
    function add_tbl_faq($params)
    {
        $this->db->insert('tbl_faq',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_faq
     */
    function update_tbl_faq($id_faq,$params)
    {
        $this->db->where('id_faq',$id_faq);
        return $this->db->update('tbl_faq',$params);
    }
    
    /*
     * function to delete tbl_faq
     */
    function delete_tbl_faq($id_faq)
    {
        return $this->db->delete('tbl_faq',array('id_faq'=>$id_faq));
    }
}
