<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Adm_users extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_admin_model');
        if (!$this->session->userdata('logged')) {            
            $this->session->set_flashdata('message','Silahkan login untuk memulai!');
            $this->session->set_flashdata('error','animated headShake red-box');
            //$this->index();
            redirect('login');
        }
    } 

    /*
     * Listing of tbl_admin
     */
    function index()
    {
        
        $data = array(
            "site" => $_SERVER['SERVER_NAME'],
            "page" => "User List",
            "tbl_admin" => $this->Tbl_admin_model->get_all_tbl_admin()
        );
        $this->load->view('layout/admin/header', $data);
        $this->load->view('index',$data);
        $this->load->view('layout/admin/footer');
    }

    /*
     * Adding a new tbl_admin
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'admin_password' => md5($this->input->post('admin_password')),
				'admin_username' => $this->input->post('admin_username'),
				'email' => $this->input->post('email'),
				'role' => $this->input->post('role'),
            );
            
            $tbl_admin_id = $this->Tbl_admin_model->add_tbl_admin($params);
            if($tbl_admin_id)
            {
                $this->session->set_flashdata('pesan', 'toastr.success("Berhasil Menambah User", "Success");');
            }else{
                $this->session->set_flashdata('pesan', 'toastr.error("Gagal Menambah User", "Error");');
            }
            redirect('admin/users');
        }
        else
        {
            $data = array(
                "site" => $_SERVER['SERVER_NAME'],
                "page" => "User Add",
                "tbl_admin" => $this->Tbl_admin_model->get_all_tbl_admin()
            );
            $this->load->view('layout/admin/header', $data);
            $this->load->view('add',$data);
            $this->load->view('layout/admin/footer');
        }
    }  

    /*
     * Editing a tbl_admin
     */
    function edit($id_admin)
    {   
        // check if the tbl_admin exists before trying to edit it
        $data['tbl_admin'] = $this->Tbl_admin_model->get_tbl_admin($id_admin);
        
        if(isset($data['tbl_admin']['id_admin']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'admin_username' => $this->input->post('admin_username'),
					'email' => $this->input->post('email'),
					'role' => $this->input->post('role'),
                );

                $tbl_admin_id = $this->Tbl_admin_model->update_tbl_admin($id_admin,$params);
                if($tbl_admin_id)
                {
                    $this->session->set_flashdata('pesan', 'toastr.success("Berhasil Mengubah User", "Success");');
                }else{
                    $this->session->set_flashdata('pesan', 'toastr.error("Gagal Mengubah User", "Error");');
                }    
                redirect('admin/users');
            }
            else
            {
                $data = array(
                    "site" => $_SERVER['SERVER_NAME'],
                    "page" => "User Edit",
                    "tbl_admin" => $this->Tbl_admin_model->get_tbl_admin($id_admin)
                );
                $this->load->view('layout/admin/header', $data);
                $this->load->view('edit',$data);
                $this->load->view('layout/admin/footer');
            }
        }
        else
            show_error('The tbl_admin you are trying to edit does not exist.');
    } 
    function changepasswd()
    {
        $id_admin = $this->session->userdata('id_admin');
        $data['tbl_admin'] = $this->Tbl_admin_model->get_tbl_admin($id_admin);
        
        if(isset($data['tbl_admin']['id_admin']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $oldpassword = $this->input->post('oldpassword');
                $password = $this->input->post('password');
                $repassword = $this->input->post('repassword');
                $get_passwd = $this->Tbl_admin_model->get_tbl_admin_passwd($id_admin, $oldpassword);
                if(isset($get_passwd['id_admin']))
                {
                    if(strtoupper($password) == strtoupper($repassword))
                    {
                        $params = array('admin_password' => md5($password));
                        $tbl_admin_id = $this->Tbl_admin_model->update_tbl_admin($id_admin,$params);
                        if($tbl_admin_id)
                        {
                            $this->session->set_flashdata('pesan', 'toastr.success("Berhasil Mengubah Password", "Success");');
                            redirect('admin/users');
                        }else{
                            $this->session->set_flashdata('pesan', 'toastr.error("Gagal Mengubah Password", "Error");');
                            redirect('admin/users');
                        }    
                    }else{
                        $this->session->set_flashdata('pesan', 'toastr.error("Password Tidak Sesuai", "Error");');
                        redirect('admin/users');
                    }
                }
                
            }
        }
        else
            show_error('The tbl_admin you are trying to edit does not exist.');
    }

    /*
     * Deleting tbl_admin
     */
    function remove($id_admin)
    {
        $tbl_admin = $this->Tbl_admin_model->get_tbl_admin($id_admin);

        // check if the tbl_admin exists before trying to delete it
        if(isset($tbl_admin['id_admin']))
        {
            $this->Tbl_admin_model->delete_tbl_admin($id_admin);
            $this->session->set_flashdata('pesan', 'toastr.success("Berhasil Menghapus User", "Success");');
            redirect('admin/users');
        }
        else
            $this->session->set_flashdata('pesan', 'toastr.error("Gagal Menghapus User", "Error");');
            show_error('The tbl_admin you are trying to delete does not exist.');
    }
    
}
