<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_activity_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_activity by id_activity
     */
    function get_tbl_activity($id_activity)
    {
        return $this->db->get_where('tbl_activity',array('id_activity'=>$id_activity))->row_array();
    }
        
    /*
     * Get all tbl_activity
     */
    function get_all_tbl_activity()
    {
        $this->db->order_by('id_activity', 'desc');
        return $this->db->get('tbl_activity')->result_array();
    }
        
    /*
     * function to add new tbl_activity
     */
    function get_tbl_activity_id($id_activity)
    {
        $this->db->where('id_activity', $id_activity);
        return $this->db->get('tbl_activity_img');
    }


    function get_tbl_activity_img($id_activity)
    {
        return $this->db->get_where('tbl_activity_img',array('id_img'=>$id_activity))->row_array();
    }


    function add_tbl_activity($params)
    {
        $this->db->insert('tbl_activity',$params);
        $insert_id = $this->db->insert_id();
        return $insert_id;
    }
    
    /*
     * function to update tbl_activity
     */
    function update_tbl_activity($id_activity,$params)
    {
        $this->db->where('id_activity',$id_activity);
        return $this->db->update('tbl_activity',$params);
    }
    
    /*
     * function to delete tbl_activity
     */
    function delete_tbl_activity($id_activity)
    {
        return $this->db->delete('tbl_activity_img',array('id_activity'=>$id_activity));
    }
    function delete_tbl_activity_img($id_img)
    {
        return $this->db->delete('tbl_activity_img',array('id_img'=>$id_img));
    }
}
