<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_history_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_processing by id_home
     */
    function get_tbl_processing()
    {
        return $this->db->get_where('tbl_processing',array('id_processing' => 1))->row_array();
    }

    function get_tbl_history()
    {
        return $this->db->get_where('tbl_history',array('id_history' => 1))->row_array();
    }
    
    /*
     * function to update tbl_processing
     */
    function update_tbl_processing($params)
    {
        $this->db->where('id_processing', 1);
        return $this->db->update('tbl_processing',$params);
    }
    function update_tbl_history($params)
    {
        $this->db->where('id_history', 1);
        return $this->db->update('tbl_history',$params);
    }

    /*
     * Get last tbl_processing
     */
    function get_last_tbl_processing()
    {
        return $this->db->get('tbl_processing')->last_query();
    }
        
    /*
     * function to add new tbl_processing
     */
    function add_tbl_processing($params)
    {
        $this->db->insert('tbl_processing',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to delete tbl_processing
     */
    function delete_tbl_processing($id_home)
    {
        $this->db->delete('tbl_processing_img',array('id_home'=>$id_home));
        return $this->db->delete('tbl_processing',array('id_home'=>$id_home));
    }
}
