<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Adm_home_slider extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_slider_model');
        if (!$this->session->userdata('logged')) {            
            $this->session->set_flashdata('message','Silahkan login untuk memulai!');
            $this->session->set_flashdata('error','animated headShake red-box');
            //$this->index();
            redirect('login');
        }
    } 

    /*
     * Listing of tbl_slider
     */
    function index()
    {
        $data = array(
            "site" => $_SERVER['SERVER_NAME'],
            "page" => "Home Slider",
            "tbl_slider" => $this->Tbl_slider_model->get_all_tbl_slider()
        );
        
        $this->load->view('layout/admin/header', $data);
        $this->load->view('index', $data);
        $this->load->view('layout/admin/footer');
    }

    /*
     * Adding a new tbl_slider
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $config['upload_path']          = './uploads/';
            $config['allowed_types']        = 'gif|jpg|png|jpeg';
            $config['max_size']             = 0;
            $config['max_width']            = 0;
            $config['max_height']           = 0;

            $this->load->library('upload', $config);

            if ( ! $this->upload->do_upload('slider_img'))
            {
                $params = array(
                    'slider_title_id' => $this->input->post('slider_title_id'),
                    'slider_title_en' => $this->input->post('slider_title_en'),
                    'slider_desc_id' => $this->input->post('slider_desc_id'),
                    'slider_desc_en' => $this->input->post('slider_desc_en'),
                );
                
                $tbl_slider_id = $this->Tbl_slider_model->add_tbl_slider($params);
                redirect('admin/home_slider');
            }
            else
            {
                $data = array('upload_data' => $this->upload->data());
                $params = array(
                    'slider_title_id' => $this->input->post('slider_title_id'),
                    'slider_title_en' => $this->input->post('slider_title_en'),
                    'slider_img' => $this->upload->data('file_name'),
                    'slider_desc_id' => $this->input->post('slider_desc_id'),
                    'slider_desc_en' => $this->input->post('slider_desc_en'),
                );
                
                $tbl_slider_id = $this->Tbl_slider_model->add_tbl_slider($params);
                redirect('admin/home_slider');
            }
        }
        else
        {            
            $data = array(
                "site" => $_SERVER['SERVER_NAME'],
                "page" => "Home Slider"
            );
            
            $this->load->view('layout/admin/header', $data);
            $this->load->view('add', $data);
            $this->load->view('layout/admin/footer');
        }
    }  

    /*
     * Editing a tbl_slider
     */
    function edit($id_slider)
    {   
        // check if the tbl_slider exists before trying to edit it
        $data['tbl_slider'] = $this->Tbl_slider_model->get_tbl_slider($id_slider);
        
        if(isset($data['tbl_slider']['id_slider']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {         
                $config['upload_path']          = './uploads/';
                $config['allowed_types']        = 'gif|jpg|png';
                $config['max_size']             = 100;
                $config['max_width']            = 1024;
                $config['max_height']           = 768;

                $this->load->library('upload', $config);

                if ( ! $this->upload->do_upload('slider_img'))
                {
                    $params = array(
                        'slider_title_id' => $this->input->post('slider_title_id'),
                        'slider_title_en' => $this->input->post('slider_title_en'),
                        'slider_desc_id' => $this->input->post('slider_desc_id'),
                        'slider_desc_en' => $this->input->post('slider_desc_en'),
                    );
                    
                    $this->Tbl_slider_model->update_tbl_slider($id_slider,$params);
                    redirect('admin/home_slider');
                }
                else
                {
                    $data = array('upload_data' => $this->upload->data());
                    $params = array(
                        'slider_title_id' => $this->input->post('slider_title_id'),
                        'slider_title_en' => $this->input->post('slider_title_en'),
                        'slider_img' => $this->upload->data('file_name'),
                        'slider_desc_id' => $this->input->post('slider_desc_id'),
                        'slider_desc_en' => $this->input->post('slider_desc_en'),
                    );
                    
                    $this->Tbl_slider_model->update_tbl_slider($id_slider,$params);
                    redirect('admin/home_slider');
                }
            }
            else
            {
                $data = array(
                    "site" => $_SERVER['SERVER_NAME'],
                    "page" => "Home Slider",
                    "tbl_slider" => $this->Tbl_slider_model->get_tbl_slider($id_slider)
                );
                
                $this->load->view('layout/admin/header', $data);
                $this->load->view('edit', $data);
                $this->load->view('layout/admin/footer');
            }
        }
        else
            show_error('The tbl_slider you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_slider
     */
    function remove($id_slider)
    {
        $tbl_slider = $this->Tbl_slider_model->get_tbl_slider($id_slider);

        // check if the tbl_slider exists before trying to delete it
        if(isset($tbl_slider['id_slider']))
        {
            unlink('./uploads/'.$tbl_slider['slider_img']);
            $this->Tbl_slider_model->delete_tbl_slider($id_slider);
            redirect('admin/home_slider');
        }
        else
            show_error('The tbl_slider you are trying to delete does not exist.');
    }
    
}
