<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_joinus_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_joinus by id_joinus
     */
    function get_tbl_joinus($id_joinus)
    {
        return $this->db->get_where('tbl_joinus',array('id_joinus'=>$id_joinus))->row_array();
    }
        
    /*
     * Get all tbl_joinus
     */
    function get_all_tbl_joinus()
    {
        $this->db->order_by('id_joinus', 'desc');
        return $this->db->get('tbl_joinus')->result_array();
    }
        
    /*
     * function to add new tbl_joinus
     */
    function add_tbl_joinus($params)
    {
        $this->db->insert('tbl_joinus',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_joinus
     */
    function update_tbl_joinus($id_joinus,$params)
    {
        $this->db->where('id_joinus',$id_joinus);
        return $this->db->update('tbl_joinus',$params);
    }
    
    /*
     * function to delete tbl_joinus
     */
    function delete_tbl_joinus($id_joinus)
    {
        return $this->db->delete('tbl_joinus',array('id_joinus'=>$id_joinus));
    }
}
