<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_video_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_video by id_video
     */
    function get_tbl_video($id_video)
    {
        return $this->db->get_where('tbl_video',array('id_video'=>$id_video))->row_array();
    }
        
    /*
     * Get all tbl_video
     */
    function get_all_tbl_video()
    {
        $this->db->order_by('id_video', 'desc');
        return $this->db->get('tbl_video');
    }
        
    /*
     * function to add new tbl_video
     */
    function get_tbl_video_id()
    {
        $this->db->where('id_video');
        return $this->db->get('tbl_video');
    }


    function get_tbl_video_img($id_video)
    {
        return $this->db->get_where('tbl_video',array('id_video'=>$id_video))->row_array();
    }


    function add_tbl_video($params)
    {
        $this->db->insert('tbl_video',$params);
        $insert_id = $this->db->insert_id();
        return $insert_id;
    }
    
    /*
     * function to update tbl_video
     */
    function update_tbl_video($id_video,$params)
    {
        $this->db->where('id_video',$id_video);
        return $this->db->update('tbl_video',$params);
    }
    
    /*
     * function to delete tbl_video
     */
    function delete_tbl_video($id_video)
    {
        return $this->db->delete('tbl_video',array('id_video'=>$id_video));
    }
    function delete_tbl_video_img($id_img)
    {
        return $this->db->delete('tbl_video',array('id_video'=>$id_img));
    }
}
