<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Adm_video extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_video_model');
        if (!$this->session->userdata('logged')) {            
            $this->session->set_flashdata('message','Silahkan login untuk memulai!');
            $this->session->set_flashdata('error','animated headShake red-box');
            //$this->index();
            redirect('login');
        }
    } 

    /*
     * Listing of tbl_video
     */
    function index()
    {
        $data = array(
            "site" => $_SERVER['SERVER_NAME'],
            "page" => "video",
            "tbl_video" => $this->Tbl_video_model->get_all_tbl_video()
        );
        
        $this->load->view('layout/admin/header', $data);
        $this->load->view('index', $data);
        $this->load->view('layout/admin/footer');
    }

    function video_upload()
    {
        if (!empty($_FILES)) {
            $tempFile = $_FILES['file']['tmp_name'];
            $fileName = $_FILES['file']['name'];
            $fileName = rand(1,1000).md5($fileName).'_'.$fileName;
            $targetPath = getcwd() . '/uploads/';
            $targetFile = $targetPath . $fileName ;
            move_uploaded_file($tempFile, $targetFile);
            // if you want to save in db,where here
            // with out model just for example
            $this->load->database(); // load database
            $this->db->insert('tbl_video',array('video' => $fileName));
            redirect('admin/video_upload/'.$id_video);
        }
        else
        {            
            $data = array(
                "site" => $_SERVER['SERVER_NAME'],
                "page" => "Video Upload",
                "video" => $this->Tbl_video_model->get_all_tbl_video(),
            );
            
            $this->load->view('layout/admin/header', $data);
            $this->load->view('upload', $data);
            $this->load->view('layout/admin/footer');
        }
    }

    function remove_upload($id_video)
    {
        $tbl_video = $this->Tbl_video_model->get_tbl_video_img($id_video);

        // check if the tbl_home exists before trying to delete it
        if(isset($tbl_video['id_video']))
        {   
            unlink('/home/sayuransiapsaji/public_html/uploads/'.$tbl_video['video']);
            $this->Tbl_video_model->delete_tbl_video_img($id_video);
            redirect('admin/video_upload/'.$id_video);
            
        }
        else
            show_error('The home you are trying to delete does not exist.');
    }

    /*
     * Editing a tbl_video
     */
    function edit($id_video)
    {   
        // check if the tbl_video exists before trying to edit it
        $data['tbl_video'] = $this->Tbl_video_model->get_tbl_video($id_video);
        
        if(isset($data['tbl_video']['id_video']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {         
                $config['upload_path']          = './uploads/';
                $config['allowed_types']        = 'gif|jpg|png';

                $this->load->library('upload', $config);

                if ( ! $this->upload->do_upload('video_img'))
                {
                    $params = array(
                        'video_title_id' => $this->input->post('video_title_id'),
                        'video_title_en' => $this->input->post('video_title_en'),
                        'video_desc_id' => $this->input->post('video_desc_id'),
                        'video_desc_en' => $this->input->post('video_desc_en'),
                    );
                    
                    $Tbl_video_id = $this->Tbl_video_model->update_tbl_video($id_video,$params);
                }
                else
                {
                    $data = array('upload_data' => $this->upload->data());
                    $params = array(
                        'video_title_id' => $this->input->post('video_title_id'),
                        'video_title_en' => $this->input->post('video_title_en'),
                        'video_img' => $this->upload->data('file_name'),
                        'video_desc_id' => $this->input->post('video_desc_id'),
                        'video_desc_en' => $this->input->post('video_desc_en'),
                    );
                    
                    $Tbl_video_id = $this->Tbl_video_model->update_tbl_video($id_video,$params);
                }

                if($Tbl_video_id)
                {
                    $this->session->set_flashdata('pesan', 'toastr.success("Berhasil Mengubah", "Success")');
                }else{
                    $this->session->set_flashdata('pesan', 'toastr.error("Gagal Mengubah", "Error")');
                }
                redirect('admin/video');
            }
            else
            {
                $data = array(
                    "site" => $_SERVER['SERVER_NAME'],
                    "page" => "video",
                    "tbl_video" => $this->Tbl_video_model->get_tbl_video($id_video)
                );
                
                $this->load->view('layout/admin/header', $data);
                $this->load->view('edit', $data);
                $this->load->view('layout/admin/footer');
            }
        }
        else
            show_error('The tbl_video you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_video
     */
    function remove($id_video)
    {
        $tbl_video = $this->Tbl_video_model->get_tbl_video($id_video);

        // check if the tbl_video exists before trying to delete it
        if(isset($tbl_video['id_video']))
        {
            if($tbl_video['video_img'] != '' || $tbl_video['video_img'] != null){
                unlink('/home/sayuransiapsaji/public_html/uploads/'.$tbl_video['video_img']);                
            }
            $Tbl_video_id = $this->Tbl_video_model->delete_tbl_video($id_video);
            
            if($Tbl_video_id)
            {
                $this->session->set_flashdata('pesan', 'toastr.success("Berhasil Menghapus", "Success")');
            }else{
                $this->session->set_flashdata('pesan', 'toastr.error("Gagal Menghapus", "Error")');
            }
            redirect('admin/video');
        }
        else
            show_error('The tbl_video you are trying to delete does not exist.');
    }
    
}
