<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_home_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_home by id_home
     */
    function get_tbl_home($id_home)
    {
        return $this->db->get_where('tbl_home',array('id_home'=>$id_home))->row_array();
    }
        
    /*
     * Get all tbl_home
     */
    function get_all_tbl_home()
    {
        $this->db->order_by('id_home', 'desc');
        return $this->db->get('tbl_home')->result_array();
    }

    /*
     * Get last tbl_home
     */
    function get_last_tbl_home()
    {
        return $this->db->get('tbl_home')->last_query();
    }
        
    /*
     * function to add new tbl_home
     */
    function add_tbl_home($params)
    {
        $this->db->insert('tbl_home',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_home
     */
    function update_tbl_home($id_home,$params)
    {
        $this->db->where('id_home',$id_home);
        return $this->db->update('tbl_home',$params);
    }
    
    /*
     * function to delete tbl_home
     */
    function delete_tbl_home($id_home)
    {
        $this->db->delete('tbl_home_img',array('id_home'=>$id_home));
        return $this->db->delete('tbl_home',array('id_home'=>$id_home));
    }
}
