<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_home_img_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_home_img by id_img
     */
    function get_tbl_onfarm_img($id_img)
    {
        return $this->db->get_where('tbl_onfarm_img',array('id_img'=>$id_img))->row_array();
    }
     
    function delete_tbl_onfarm_img($id_img)
    {
        return $this->db->delete('tbl_onfarm_img',array('id_img'=>$id_img));
    }

    function get_all_tbl_onfarm_img()
    {
        $this->db->order_by('id_img', 'desc');
        return $this->db->get('tbl_onfarm_img');
    }

    function get_tbl_processing_img($id_img)
    {
        return $this->db->get_where('tbl_processing_img',array('id_img'=>$id_img))->row_array();
    }
     
    function delete_tbl_processing_img($id_img)
    {
        return $this->db->delete('tbl_processing_img',array('id_img'=>$id_img));
    }

    function get_all_tbl_processing_img()
    {
        $this->db->order_by('id_img', 'desc');
        return $this->db->get('tbl_processing_img');
    }
    
    function insert_data($name)
    {
        $data = array('id_processing' => 1, 'image' => $name);
        return $this->db->insert('tbl_processing_img', $data);
    }
        
}
