<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_profile_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_profile by id
     */
    function get_tbl_profile($id)
    {
        return $this->db->get_where('tbl_profile',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_profile
     */
    function get_all_tbl_profile()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_profile')->result_array();
    }
        
    /*
     * function to add new tbl_profile
     */
    function add_tbl_profile($params)
    {
        $this->db->insert('tbl_profile',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_profile
     */
    function update_tbl_profile($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_profile',$params);
    }
    
    /*
     * function to delete tbl_profile
     */
    function delete_tbl_profile($id)
    {
        return $this->db->delete('tbl_profile',array('id'=>$id));
    }
}
