<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Adm_home_img extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->database(); // load database
        $this->load->model(array('Tbl_home_model','Tbl_home_img_model'));
        
        if (!$this->session->userdata('logged')) {            
            $this->session->set_flashdata('message','Silahkan login untuk memulai!');
            $this->session->set_flashdata('error','animated headShake red-box');
            //$this->index();
            redirect('login');
        }
    } 

    function add_processing()
    {   
        if (!empty($_FILES)) {
            $tempFile = $_FILES['file']['tmp_name'];
            $fileName = $_FILES['file']['name'];
            $targetPath = '/home/sayuransiapsaji/public_html/uploads/';
            $targetFile = $targetPath . $fileName ;
            move_uploaded_file($tempFile, $targetFile);
            // if you want to save in db,where here
            // with out model just for example
            $this->Tbl_home_img_model->insert_data($fileName);
            redirect('admin/processing_img');
        }
        else
        {            
            $data = array(
                "site" => $_SERVER['SERVER_NAME'],
                "page" => "Upload Processing",
                "image" => $this->Tbl_home_img_model->get_all_tbl_processing_img()
            );
            
            $this->load->view('layout/admin/header', $data);
            $this->load->view('upload-processing', $data);
            $this->load->view('layout/admin/footer');
        }
    }


    function remove_processing($id_img)
    {
        $tbl_home_img = $this->Tbl_home_img_model->get_tbl_processing_img($id_img);

        // check if the tbl_processing_img exists before trying to delete it
        if(isset($tbl_home_img['id_img']))
        {
            unlink('./uploads/'.$tbl_home_img['image']);
            $this->Tbl_home_img_model->delete_tbl_processing_img($id_img);
            redirect('admin/processing_img');
        }
        else
            show_error('The tbl_home_img you are trying to delete does not exist.');
    }

    function add_onfarm()
    {   
        if (!empty($_FILES)) {
            $tempFile = $_FILES['file']['tmp_name'];
            $fileName = $_FILES['file']['name'];
            $targetPath = getcwd() . '/uploads/';
            $targetFile = $targetPath . $fileName ;
            move_uploaded_file($tempFile, $targetFile);
            // if you want to save in db,where here
            // with out model just for example
            $this->load->database(); // load database
            $this->db->insert('tbl_onfarm_img',array('id_onfarm' => 1, 'image' => $fileName));
            redirect('admin/onfarm_img');
        }
        else
        {            
            $data = array(
                "site" => $_SERVER['SERVER_NAME'],
                "page" => "Image OnFarm",
                "image" => $this->Tbl_home_img_model->get_all_tbl_onfarm_img()
            );
            
            $this->load->view('layout/admin/header', $data);
            $this->load->view('upload-onfarm', $data);
            $this->load->view('layout/admin/footer');
        }
    }  


    function remove_onfarm($id_img)
    {
        $tbl_home_img = $this->Tbl_home_img_model->get_tbl_onfarm_img($id_img);

        // check if the tbl_processing_img exists before trying to delete it
        if(isset($tbl_home_img['id_img']))
        {

            if($tbl_home_img['image'] != '' || $tbl_home_img['image'] != null){
                unlink('/home/sayuransiapsaji/public_html/uploads/'.$tbl_home_img['image']);                
            }
            $Tbl_product_id = $this->Tbl_home_img_model->delete_tbl_onfarm_img($id_img);
            
            if($Tbl_product_id)
            {
                $this->session->set_flashdata('pesan', 'toastr.success("Berhasil Menghapus Produk", "Success")');
            }else{
                $this->session->set_flashdata('pesan', 'toastr.error("Gagal Menghapus Produk", "Error")');
            }
            
            redirect('admin/onfarm_img');
        }
        else
            show_error('The tbl_home_img you are trying to delete does not exist.');
    }
}
